language: rust
sudo: required
dist: trusty
rust:
  - nightly
cache: cargo
addons:
  postgresql: '9.5'
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build
matrix:
  include:
  - rust: nightly
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/